name: Samantha
on: push
jobs: 
  vijay: 
    runs-on: ubuntu-latest
    steps: 
      - name: Printing TvK
        run: echo "Tvk Vazhga!!!"
      - name:Printing DMK
        run: echo "DMK oru theeya shakthi!!!"