name: Samantha
on: workflow_dispatch
jobs: 
  vijay: 
    runs-on: ubuntu-latest
    steps: 
      - name: Printing TvK
        run: echo "Tvk Vazhga!!!"
      - name: Printing DMK
        run: | 
          echo "DMK oru theeya shakthi!!!"
          echo "DMK uncle"

  surya:
      runs-on: ubuntu-latest
      steps:
        - name: printing hello 
          run: echo "hello this is surya"